# Generated by Django 4.0.6 on 2022-07-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
            ],
        ),
    ]
