# Generated by Django 4.0.6 on 2022-07-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_convert_participant_alter_location_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convert',
            name='program',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='program',
        ),
    ]
