# Generated by Django 4.0.6 on 2022-07-29 13:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_remove_convert_program_remove_participant_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
