# Generated by Django 4.0.6 on 2022-08-20 01:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('', 'Select gender'), ('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('age', models.CharField(choices=[('', 'Select age group'), ('16-20', '16-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('30-35', '30-35'), ('36-40', '36-40'), ('41-45', '41-45'), ('46-50', '46-50'), ('51-55', '51-55'), ('56-60', '56-60'), ('Above 60', 'Above 60')], max_length=10, null=True, verbose_name='Age')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('category', models.CharField(choices=[('', 'Select category'), ('ENT', 'Enterprenuer'), ('UNGRAD', 'Undergraduate'), ('GRAD', 'Graduate'), ('CORP', 'Corper'), ('PRIVATE/GOVR', 'Private/Goverment Worker'), ('YOUNG PROF', 'Young Professionals'), ('RES', 'Researcher'), ('TERT STAFF', 'Tertiary Institution Worker'), ('POST SEC', 'Post Secondary School Student')], max_length=20, null=True, verbose_name='Category')),
                ('school', models.CharField(max_length=100, null=True, verbose_name='School/Work Address')),
                ('denomination', models.CharField(choices=[('', 'Select denomination'), ('DLCB', 'Depper Life Bible Church'), ('RCCG', 'Redeem Christian Church Of God'), ('CAC', 'Christ Apostolic Church'), ('AF', 'Apostolic Faith'), ('MFM', 'Mountain Of Fire'), ('GOFAMINT', 'Gospel Faith Mission'), ('WC', 'Winners Chapel'), ('CATH', 'Catholic'), ('ANG', 'Anglican Church'), ('BAP', 'Baptist Church')], max_length=10, null=True, verbose_name='Denomination')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=32, verbose_name='Region')),
                ('groups', models.CharField(max_length=32, verbose_name='Group')),
                ('districts', models.CharField(max_length=32, verbose_name='District')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('', 'Select gender'), ('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('age', models.CharField(choices=[('', 'Select age group'), ('16-20', '16-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('30-35', '30-35'), ('36-40', '36-40'), ('41-45', '41-45'), ('46-50', '46-50'), ('51-55', '51-55'), ('56-60', '56-60'), ('Above 60', 'Above 60')], max_length=10, null=True, verbose_name='Age')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('linkedin', models.CharField(max_length=60, null=True, verbose_name='LinkedIn')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('regions', models.CharField(max_length=32, verbose_name='District')),
                ('groups', models.CharField(max_length=32, verbose_name='Group')),
                ('districts', models.CharField(max_length=32, verbose_name='District')),
                ('category', models.CharField(choices=[('', 'Select category'), ('ENT', 'Enterprenuer'), ('UNGRAD', 'Undergraduate'), ('GRAD', 'Graduate'), ('CORP', 'Corper'), ('PRIVATE/GOVR', 'Private/Goverment Worker'), ('YOUNG PROF', 'Young Professionals'), ('RES', 'Researcher'), ('TERT STAFF', 'Tertiary Institution Worker'), ('POST SEC', 'Post Secondary School Student')], max_length=20, null=True, verbose_name='Category')),
                ('school', models.CharField(max_length=100, null=True, verbose_name='School/Work Address')),
                ('denomination', models.CharField(choices=[('', 'Select denomination'), ('DLCB', 'Depper Life Bible Church'), ('RCCG', 'Redeem Christian Church Of God'), ('CAC', 'Christ Apostolic Church'), ('AF', 'Apostolic Faith'), ('MFM', 'Mountain Of Fire'), ('GOFAMINT', 'Gospel Faith Mission'), ('WC', 'Winners Chapel'), ('CATH', 'Catholic'), ('ANG', 'Anglican Church'), ('BAP', 'Baptist Church')], max_length=10, null=True, verbose_name='Denomination')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=32, verbose_name='Region')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
