# Generated by Django 4.0.6 on 2022-09-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, verbose_name='state')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='regions',
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='City/Town'),
        ),
        migrations.AlterField(
            model_name='region',
            name='regions',
            field=models.CharField(max_length=32, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='region',
            name='states',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='custom_admin.state'),
        ),
    ]
