# Generated by Django 4.0.6 on 2022-09-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_alter_participant_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convert',
            options={'ordering': ['-registered_date'], 'verbose_name': 'convert', 'verbose_name_plural': 'converts'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-registered_date'], 'verbose_name': 'participant', 'verbose_name_plural': 'participants'},
        ),
    ]
