# Generated by Django 4.0.6 on 2022-09-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_state_delete_location_remove_participant_districts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='participant',
            name='region',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_region', to='custom_admin.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='state',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_state', to='custom_admin.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='regions',
            field=models.CharField(max_length=32, verbose_name='regions'),
        ),
        migrations.AlterField(
            model_name='region',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_state', to='custom_admin.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=20, verbose_name='states'),
        ),
    ]
