# Generated by Django 4.0.6 on 2022-09-28 19:11

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_state_options_participant_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='regions',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='states',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='participant',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='custom_admin.region'),
        ),
    ]
