# Generated by Django 4.0.6 on 2022-09-29 15:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_rename_regions_region_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='convert',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', default=3, on_delete=django.db.models.deletion.CASCADE, to='custom_admin.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convert',
            name='state',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_state', to='custom_admin.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='custom_admin.region'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='convert_state', to='custom_admin.state'),
        ),
    ]
